DROP TABLE IF EXISTS SAWMILL;
CREATE TABLE SAWMILL (
    id   INTEGER  NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL UNIQUE,
    city VARCHAR(120),
    country VARCHAR(120),
    created_at DATETIME,
    updated_at DATETIME,
    PRIMARY KEY (id)
);